# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
      - name: Check out code
        uses: actions/checkout@v4
      # This project doesn't have any dependencies
      #- name: Install dependencies
      #  run: |
      #    go mod download
      - name: Run Unit tests
        run: |
          go test -race -covermode atomic -coverprofile=covprofile ./pkg/...
      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github
      #- name: Upload coverage reports to Codecov
      #  uses: codecov/codecov-action@v4.0.1
      #  with:
      #    token: ${{ secrets.CODECOV_TOKEN }}